services:
  monapache:
    # image perso du binôme
    image: mathieuballin/monapache
    volumes:
      - .:/var/www/html
    ports:
      - 80:80

  mariadb:
    # image officielle mariadb
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=&{LOGIN_BD}
      - MYSQL_DATABASE=&{PASS_BD}
      - MYSQL_USER=&{NOM_BD}
      - MYSQL_PASSWORD=&{PASS_ROOT_BD}
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    # image officielle phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
  
  monubuntu:
    # image perso du binôme
    image: mathieuballin/monubuntu
